service:
    name: deploy-worker-github-action
    config:
      accountId: e0e0323ad86f07e674d7e74991733f0e
      zoneId: f356570df549a8058f82d0edac7257fe

provider:
  name: cloudflare

plugins:
  - serverless-cloudflare-workers
  
functions:
  worker-deploy:
    name: epg
    script: index.js
