name: Deploy to Cloudflare Workers

on:
  workflow_dispatch: {}
  push: 
    branches:
      - main
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Install Wrangler CLI
      uses: cloudflare/wrangler-action@1.3.0
      with:
        command: install

    - name: Publish to Cloudflare Workers
      uses: cloudflare/wrangler-action@1.3.0
      with:
        apiToken: rlfUpmp_shNIZ-0Zo84z458nxQyrmpIdwEHSuooY
        accountId: e0e0323ad86f07e674d7e74991733f0e
        command: publish
