name: Deploy Worker

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Wrangler
        #run: npm install -g @cloudflare/wrangler
        run: npm install -g wrangler
      
      - name: Configure Wrangler
        run: wrangler config --api-token rlfUpmp_shNIZ-0Zo84z458nxQyrmpIdwEHSuooY
      
      - name: Publish Worker
        run: wrangler publish
