name: Deploy Worker

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Wrangler
        run: npm install -g @cloudflare/wrangler
      - name: Configure Wrangler
        env:
          CF_API_TOKEN: rlfUpmp_shNIZ-0Zo84z458nxQyrmpIdwEHSuooY
        run: wrangler config --api-token $CF_API_TOKEN
      - name: Publish Worker
        run: wrangler publish
